### PR TITLE
Fixed pydev for alpine instances

### PR DESCRIPTION
**Pull request by matllubos**

### CODE REVIEW

**Comment by radimsuckr** [comment]
Alpine instances? Didn't you mean running standalone commands without shell? 😁

**Comment by matllubos** [comment]
No I really think alpine instances. Because in alpine the separator between shell commands works little bit diferently. It can be some weird alpine bug, but If you pass the command with spaces it will fail. The same commands with the debian or other linux image work

**Comment by matllubos** [comment]
I have the same bug with the alpine in skippay project before

**Comment by radimsuckr** [comment]
OK, anyways LGTM 🚀 😃

**Review by radimsuckr — APPROVED** [review]

**Pull request closed without merging**
